version: '3'

services:
  webserver:
    image: nginx:1.25
    volumes:
      - ./.docker/nginx/:/etc/nginx/conf.d/
      - ./public:/usr/share/nginx/html
    ports:
      - 8080:80
  php-fpm:
    build:
      context: .docker/php/
    volumes:
      - ./public:/usr/share/nginx/html
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - database-data:/var/lib/mysql
  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8088:8080

volumes:
  database-data: ~
