version: '3'

services:
  php:
    build:
      context: .docker/php/
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - database-data:/var/lib/mysql
  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8088:8080

volumes:
  database-data: ~
