version: '3'

services:
  webserver:
    image: nginx:1.25
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    ports:
      - 8080:80
  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./public:/usr/share/nginx/html
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - database-data:/var/lib/mysql
  adminer:
    image: adminer:4
    ports:
      - 8088:8080

volumes:
  database-data: ~
