version: '3'

services:
  php:
    image: ghcr.io/sfenitv/container-images/php:v0.0.4
    volumes:
      - ./app:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-app.ini
    ports:
      - 8080:80
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: app
      MYSQL_USER: myuser
      MYSQL_PASSWORD: pwd123
    volumes:
      - database-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5-apache
    environment:
      PMA_HOST: database
      PMA_USER: myuser
      PMA_PASSWORD: pwd123
    ports:
      - 8088:80

volumes:
  database-data: ~
